name: alpha-monitor

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install deps
        run: pip install -r requirements.txt

      - name: run script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python main.py
